version: 2
workflows:
  version: 2
  test:
    jobs:
      - test-3.10
      - test-3.9
      - test-3.8
      - test-3.7
      - test-pylint
      - test-black

jobs:
  test-3.7: &test-template
    docker:
      - image: cimg/python:3.7
    environment:
      - TOX_ENV: py37
    working_directory: ~/wryte
    steps:
      - checkout
      - run:
          name: Install test requirements
          command: |
            python3 -m venv .venv
            . .venv/bin/activate
            pip install -r dev-requirements.txt
      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "setup.py" }}-{{ checksum "dev-requirements.txt" }}
          - v2-dependencies-
      - run:
          name: Run tests
          command: |
            . .venv/bin/activate
            make testone TOX_ENV=$TOX_ENV
      - run: . .venv/bin/activate && pip install codecov && codecov
      - save_cache:
          paths:
            - .tox/$TOX_ENV
          key: v2-dependencies-{{ checksum "setup.py" }}-{{ checksum "dev-requirements.txt" }}

  test-3.8:
    <<: *test-template
    docker:
      - image: cimg/python:3.8
    environment:
      - TOX_ENV: py38

  test-3.9:
    <<: *test-template
    docker:
      - image: cimg/python:3.9
    environment:
      - TOX_ENV: py39

  test-3.10:
    <<: *test-template
    docker:
      - image: cimg/python:3.10
    environment:
      - TOX_ENV: py310

  test-pylint:
    <<: *test-template
    environment:
      - TOX_ENV: pylint

  test-black:
    <<: *test-template
    environment:
      - TOX_ENV: black
